"""
Django settings for excel_form_app project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path  # Used to handle filesystem paths in an OS-independent way

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mkiu+ph5%jsbi(6+9jhxu)py)en@(h8m=g%ve+z31j&eezkiq9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Enables debug mode (should be False in production)

ALLOWED_HOSTS = []  # List of allowed host/domain names for the project


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',        # Admin site
    'django.contrib.auth',         # Authentication framework
    'django.contrib.contenttypes', # Content type system
    'django.contrib.sessions',     # Session framework
    'django.contrib.messages',     # Messaging framework
    'django.contrib.staticfiles',  # Static file handling
    'main'                         # Custom application
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',          # Security-related middleware
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session handling
    'django.middleware.common.CommonMiddleware',              # Common HTTP middleware
    'django.middleware.csrf.CsrfViewMiddleware',              # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',# Authentication support
    'django.contrib.messages.middleware.MessageMiddleware',   # Messaging support
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Clickjacking protection
]

ROOT_URLCONF = 'excel_form_app.urls'  # Root URL configuration module

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # Template engine
        'DIRS': [BASE_DIR / "templates"],  # Project-level templates directory
        'APP_DIRS': True,                  # Enable app-level templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Adds request to templates
                'django.contrib.auth.context_processors.auth', # Adds user/auth data
                'django.contrib.messages.context_processors.messages', # Adds messages
            ],
        },
    },
]

WSGI_APPLICATION = 'excel_form_app.wsgi.application'  # WSGI entry point


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # PostgreSQL database engine
        'NAME': 'books',                            # Database name
        'USER': 'postgres',                         # Database user
        'PASSWORD': 'Enter_your_password',          # Database password
        'HOST': 'localhost',                        # Database host
        'PORT': '5432',                             # Database port
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Prevents similar passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Enforces minimum password length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # Prevents common passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',# Prevents numeric-only passwords
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Default language

TIME_ZONE = 'UTC'  # Time zone setting

USE_I18N = True  # Enable internationalization

USE_TZ = True  # Enable timezone-aware datetimes


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'  # URL prefix for static files
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Project-level static files directory
]

LOGIN_REDIRECT_URL = 'home'   # Redirect after successful login
LOGOUT_REDIRECT_URL = 'home'  # Redirect after logout

LOGIN_URL = 'login'  # URL used for login
